#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=${LC_ALL:-C}
export TZ=${TZ:-UTC}
export PYTHONHASHSEED=${PYTHONHASHSEED:-0}
export GZIP=${GZIP:--n}
export OMP_NUM_THREADS=${OMP_NUM_THREADS:-1}
export OPENBLAS_NUM_THREADS=${OPENBLAS_NUM_THREADS:-1}
echo "ENVCONTRACT GZIP=${GZIP}"
echo "ENVCONTRACT LANG=${LANG:-}"
echo "ENVCONTRACT LC_ALL=${LC_ALL}"
echo "ENVCONTRACT OMP_NUM_THREADS=${OMP_NUM_THREADS}"
echo "ENVCONTRACT OPENBLAS_NUM_THREADS=${OPENBLAS_NUM_THREADS}"
echo "ENVCONTRACT PYTHONHASHSEED=${PYTHONHASHSEED}"
echo "ENVCONTRACT PYTHONNOUSERSITE=${PYTHONNOUSERSITE:-}"
echo "ENVCONTRACT TZ=${TZ}"
